kind: pipeline
name: compatibility

clone:
    depth: 1

steps:
    - name: app-code-check
      image: nextcloudci/php7.4:php7.4-2
      environment:
          APP_NAME: ldap_contacts_backend
          CORE_BRANCH: stable23
          DB: sqlite
      commands:
          - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
          - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
          - cd ../server
          - ./occ app:check-code $APP_NAME -c strong-comparison -c deprecation
          - cd apps/$APP_NAME/
    -   name: syntax-php7.3
        image: nextcloudci/php7.3:php7.3-5
        environment:
            APP_NAME: ldap_contacts_backend
            CORE_BRANCH: master
            DB: sqlite
        commands:
            - composer install
            - ./vendor/bin/parallel-lint --exclude ./vendor/ .
    -   name: syntax-php7.4
        image: nextcloudci/php7.4:php7.4-2
        environment:
            APP_NAME: ldap_write_support
            CORE_BRANCH: master
            DB: sqlite
        commands:
            - composer install
            - ./vendor/bin/parallel-lint --exclude ./vendor/ .

type: docker
trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: tests-stable23

clone:
    depth: 1

steps:
    - name: php7.3
      image: nextcloudci/php7.3:php7.3-5
      environment:
          APP_NAME: ldap_contacts_backend
          CORE_BRANCH: stable23
          DB: sqlite
      commands:
          - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
          - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
          - cd ../server/apps/$APP_NAME
          - composer install
          - cd tests/phpunit/
          - phpunit --configuration phpunit.xml
    - name: php7.4
      image: nextcloudci/php7.4:php7.4-1
      environment:
          APP_NAME: ldap_contacts_backend
          CORE_BRANCH: master
          DB: sqlite
      commands:
          - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
          - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
          - cd ../server/apps/$APP_NAME
          - composer install
          - cd tests/phpunit/
          - phpunit --configuration phpunit.xml

trigger:
    branch:
        - master
        - stable*
    event:
        - pull_request
        - push

type: docker
